# Generated by Django 2.1.5 on 2019-07-29 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShorterUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=50)),
                ('original_url', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 7, 29, 16, 34, 29, 75486, tzinfo=utc))),
                ('expired_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
